let shopItemsData = [
  {
    id: "item-1",
    name: "Check Shirt",
    price: 45,
    desc: "This is a Check Shirt",
    img: "Images/image-1.jpg",
  },
  {
    id: "item-2",
    name: "Jacket",
    price: 100,
    desc: "This is a Jacket",
    img: "Images/image-2.jpg",
  },
  {
    id: "item-3",
    name: "Plain Shirt",
    price: 50,
    desc: "This is a Plain Shirt",
    img: "Images/image-3.jpg",
  },
  {
    id: "item-4",
    name: "Suit",
    price: 450,
    desc: "This is a Check Shirt",
    img: "Images/image-4.jpg",
  },
  {
    id: "item-5",
    name: "Check Shirt",
    price: 45,
    desc: "This is a Check Shirt",
    img: "Images/image-5.jpg",
  },
  {
    id: "item-6",
    name: "T shirt",
    price: 100,
    desc: "This is T Shirt",
    img: "Images/image-6.jpg",
  },
  {
    id: "item-7",
    name: "T shirt",
    price: 50,
    desc: "This is a T Shirt",
    img: "Images/image-7.jpg",
  },
  {
    id: "item-8",
    name: "T Shirt",
    price: 45,
    desc: "This is a T Shirt",
    img: "Images/image-8.jpg",
  },
  {
    id: "item-9",
    name: "T Shirt",
    price: 60,
    desc: "This is a T Shirt",
    img: "Images/image-9.jpg",
  },
  {
    id: "item-10",
    name: "Jacket",
    price: 100,
    desc: "This is a Jacket",
    img: "Images/image-10.jpg",
  },
  {
    id: "item-11",
    name: "Plain Shirt",
    price: 50,
    desc: "This is a Plain Shirt",
    img: "Images/image-11.jpg",
  },
  {
    id: "item-12",
    name: "Cotton Shirt",
    price: 75,
    desc: "This is a Cotton Plain Shirt",
    img: "Images/image-12.jpg",
  },
];
